[features]
seeds = false
[programs.localnet]
niftyclick = "2eaxeLhmPps1oknT5M9n2gzmzfvowz49u23pFJy9Nkez"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# wallet = "/root/.config/solana/id.json"
wallet = "~/.config/solana/phantom.json"
wallet2 = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
