[features]
seeds = false
[programs.devnet]
niftyclick = "2eaxeLhmPps1oknT5M9n2gzmzfvowz49u23pFJy9Nkez"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"
# Wallet used for testing is specified in the typescript file.

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
