[features]
seeds = false
[programs.devnet]
niftyclick = "AkB78wYxMJjweth3zCeDXGqNzRSYyJa96dg2MKXt4QT9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/phantom.json"
# Wallet used for testing is specified in the typescript file.

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
